services:
    projectnext:
        extends:
            file: docker-compose.base.yml
            service: projectnext
        build:
            target: dev
        volumes:
            - ${PROJECT_ROOT:-.}/src:/usr/src/app/src
            - ${PROJECT_ROOT:-.}/src/prisma/schema:/usr/src/app/src/prisma/schema
            - ${PROJECT_ROOT:-.}/package.json:/usr/src/app/package.json
            - ${PROJECT_ROOT:-.}/package-lock.json:/usr/src/app/package-lock.json
            - ${PROJECT_ROOT:-.}/logs:/usr/src/app/logs
            - devstore:/usr/src/app/store
            - dotnext:/usr/src/app/.next
        depends_on:
            prisma:
                condition: service_completed_successfully

    db:
        extends:
            file: docker-compose.base.yml
            service: db
        ports:
            - 5432:5432
        volumes:
            - devdb:/var/lib/postgresql/data

    prisma:
        extends:
            file: docker-compose.base.yml
            service: prisma
        build:
            target: dev
        volumes:
            - ${PROJECT_ROOT:-.}/src/prisma/schema:/usr/src/app/schema
            - devstore:/usr/src/app/prismaservice/store
            - dobbelOmegaManifest:/usr/src/app/prismaservice/dobbelOmegaManifest

    nginx:
        extends:
            file: docker-compose.base.yml
            service: nginx
        ports:
            - 80:80
        volumes:
            - ${PROJECT_ROOT:-.}/containers/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
            - devstore:/usr/store
        depends_on:
            - projectnext

volumes:
    devdb:
        driver: local
    devstore:
        driver: local
    dotnext:
        driver: local
    dobbelOmegaManifest:
        driver: local
