version: '3.8'

services:
  projectnext:
    build: 
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - devstore:/usr/src/app/store
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./src/prisma/schema.prisma:/usr/src/app/src/prisma/schema.prisma
    environment:
      NODE_ENV: development
      DB_URI: ${DB_URI}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_TELEMETRY_DISABLED:  ${NEXT_TELEMETRY_DISABLED}
    depends_on:
      - db
      - prisma
    links:
      - db
    
  db:
    image: postgres:16.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - devdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'"]
      interval: 3s
      timeout: 3s
      retries: 10

  prisma:
    build: 
      context: ./src/prisma
      dockerfile: ./prismaservice/Dockerfile
      target: dev
    environment:
      NODE_ENV: development
      DB_URI: ${DB_URI}
    volumes:
      - ./src/prisma/schema.prisma:/usr/src/app/schema.prisma
      - devstore:/usr/src/app/seeder/standard_images
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  
  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - devstore:/usr/store
    depends_on:
      - projectnext
    links:
      - projectnext

volumes:
  devdb:
    driver: local
  devstore:
    driver: local
          