version: '3.8'

services:
  projectnext:
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    environment:
      PROXY_URL: ${PROXY_URL}