version: '3.8'

services:
  projectnext:
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    environment:
      DB_URI: ${DB_URI}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      NODE_ENV: production
    depends_on:
      - db
    links:
      - db
    
  db:
    image: postgres:16.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - devdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"] # kopier fra nettet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  devdb:
    driver: local
          