version: '3.8'

services:
  projectnext:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_URI: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      NODE_ENV: production

  db:
    image: postgres:16.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - proddb:/var/lib/postgresql/data

volumes:
  proddb:
    driver: local
    
