# This file is used to define the base services that are shared between dev, test and prod.
# The services are then extended in the environment-specific files.
# This way, we can avoid duplicating the configuration for the shared services.

services:
    projectnext:
        build:
            context: ${PROJECT_ROOT:-.}/
            dockerfile: ${PROJECT_ROOT:-.}/Dockerfile
        environment:
            DB_URI: ${DB_URI}
            LOG_LEVEL: ${LOG_LEVEL}
            LOG_TO_CONSOLE: ${LOG_TO_CONSOLE}
            LOG_TO_FOLDER: ${LOG_TO_FOLDER}
            LOG_MAX_FILES: ${LOG_MAX_FILES}
            NEXTAUTH_URL: ${NEXTAUTH_URL}
            NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
            PASSWORD_SALT_ROUNDS: ${PASSWORD_SALT_ROUNDS}
            PASSWORD_ENCRYPTION_KEY: ${PASSWORD_ENCRYPTION_KEY}
            API_KEY_SALT_ROUNDS: ${API_KEY_SALT_ROUNDS}
            API_KEY_ENCRYPTION_KEY: ${API_KEY_ENCRYPTION_KEY}
            FEIDE_CLIENT_ID: ${FEIDE_CLIENT_ID}
            FEIDE_CLIENT_SECRET: ${FEIDE_CLIENT_SECRET}
            MAIL_SERVER: ${MAIL_SERVER}
            MAIL_DOMAIN: ${MAIL_DOMAIN}
            DOMAIN: ${DOMAIN}
            JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
            JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
            JWT_SECRET: ${JWT_SECRET}
        depends_on:
            db:
                condition: service_healthy
            # Since prisma service is not needed by test, then dev and prod must
            # specify the prisma service as a dependency in their respective files

    db:
        image: postgres:16.0-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'"
                ]
            interval: 0.5s
            timeout: 0.5s
            retries: 60

    prisma:
        build:
            context: ${PROJECT_ROOT:-.}/src/prisma
            dockerfile: ${PROJECT_ROOT:-.}/prismaservice/Dockerfile
            args:
                SHOULD_MIGRATE: ${VEVEN_DB_URI}
        environment:
            DB_URI: ${DB_URI}
            MIGRATE_FROM_VEVEN: ${MIGRATE_FROM_VEVEN}
            VEVEN_STORE_URL: ${VEVEN_STORE_URL}
            VEVEN_DB_URI: ${VEVEN_DB_URI}
            MIGRATION_WITH_LIMITS: ${MIGRATION_WITH_LIMITS}
            PASSWORD_SALT_ROUNDS: ${PASSWORD_SALT_ROUNDS}
            PASSWORD_ENCRYPTION_KEY: ${PASSWORD_ENCRYPTION_KEY}
            API_KEY_SALT_ROUNDS: ${API_KEY_SALT_ROUNDS}
            API_KEY_ENCRYPTION_KEY: ${API_KEY_ENCRYPTION_KEY}
        depends_on:
            db:
                condition: service_healthy

    nginx:
        image: nginx:1.21.3-alpine
        depends_on:
            - projectnext