services:
    projectnext:
        extends:
            file: docker-compose.base.yml
            service: projectnext
        build:
            target: prod
        volumes:
            - store:/usr/src/app/store
            - logs:/usr/src/app/logs
            - dobbelOmegaManifest:/usr/src/app/dobbelOmegaManifest
        deploy:
            replicas: 2
        restart: always

    imageworker:
        extends:
            file: docker-compose.base.yml
            service: projectnext
        build:
            target: prod
        command: ["./node_modules/.bin/tsx", "src/worker.ts"]
        environment:
            IGNORE_SERVER_ONLY: 'true'
        volumes:
            - store:/usr/src/app/store
            - logs:/usr/src/app/logs
        deploy:
            replicas: 1
        restart: always
        depends_on:
            db:
                condition: service_healthy

    db:
        extends:
            file: docker-compose.base.yml
            service: db
        restart: always
        volumes:
            - proddb:/var/lib/postgresql/data

    nginx:
        extends:
            file: docker-compose.base.yml
            service: nginx
        restart: always
        expose:
            - "80"
        volumes:
            - ./containers/nginx/nginx.internal.conf:/etc/nginx/nginx.conf:ro
            - store:/usr/store:ro

    postfix:
        build: ${PROJECT_ROOT:-.}/containers/postfix/
        ports:
            - '587:587'
            - '25:25'
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            MY_HOSTNAME: ${MAIL_DOMAIN}
            MY_DOMAIN: ${DOMAIN}
            RELAY_HOST: ${MAIL_RELAY_HOST}
        depends_on:
            - db
        links:
            - db
        restart: always

volumes:
    proddb:
        driver: local
    store:
        driver: local
    logs:
        driver: local
    dobbelOmegaManifest:
        driver: local
