services:
    projectnext:
        extends:
            file: docker-compose.base.yml
            service: projectnext
        build:
            target: test
        tty: true # Allows for colorized output
        environment:
            DOMAIN: omega.ntnu.no
            MAIL_DOMAIN: sanctus.omega.ntnu.no
            CI: ${CI:-}
        volumes:
            - ${PROJECT_ROOT:-.}/src:/usr/src/app/src
            - ${PROJECT_ROOT:-.}/tests:/usr/src/app/tests
        depends_on:
            db:
                condition: service_healthy
    
    db:
        extends:
            file: docker-compose.base.yml
            service: db
        # Increase max connections to allow for many tests to be run in parallel.
        command: ["postgres", "-c", "max_connections=300"]
        ports:
            - 5432:5432
