version: '3.8'

services:
  projectnext:
    build: 
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./src/prisma/schema.prisma:/usr/src/app/src/prisma/schema.prisma
    environment:
      DB_URI: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      NODE_ENV: development
    depends_on:
      - db
      - prisma
    links:
      - db
    
  db:
    image: postgres:16.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - devdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'"]
      interval: 3s
      timeout: 3s
      retries: 10

  prisma:
    build: 
      context: ./src/prisma
      dockerfile: ./Dockerfile
      target: dev
    environment:
      DB_URI: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - ./src/prisma/schema.prisma:/usr/src/app/schema.prisma
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  devdb:
    driver: local
          