target: all

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
    replication_factor: 1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/blocks
  tsdb:
    dir: /data/mimir/tsdb

compactor:
  data_dir: /data/mimir/compactor

store_gateway:
  sharding_ring:
    replication_factor: 1
